#!/usr/bin/env python3
"""
LordSlack 发布前清理脚本
自动清理个人配置和敏感信息
"""

import os
import shutil
from pathlib import Path

def cleanup_for_github():
    """清理项目以准备上传到 GitHub"""
    
    print("=" * 60)
    print("🧹 LordSlack GitHub 发布前清理")
    print("=" * 60)
    print()
    
    # 要删除的目录列表
    dirs_to_remove = [
        'data',
        'configs',
        'logs',
        'temp',
        '__pycache__',
        '.pytest_cache',
        'dashboard/node_modules',
        'dashboard/dist',
        '.venv',
        'venv',
        'env',
        '.idea',
        '.vscode/settings.json',
        'node_modules',
    ]
    
    # 要删除的文件列表
    files_to_remove = [
        '.env',
        '.env.local',
        'cmd_config.json',
        'data_v4.db',
        'data_v2.db',
        'data_v3.db',
        '*.db',
        '*.sqlite',
        '*.sqlite3',
        '.DS_Store',
        'botpy.log',
        'replace_branding.py',
        'fix_remaining.py',
    ]
    
    removed_count = 0
    
    # 删除目录
    print("📁 清理目录...")
    for dir_path in dirs_to_remove:
        if os.path.exists(dir_path):
            try:
                if os.path.isdir(dir_path):
                    shutil.rmtree(dir_path)
                    print(f"  ✓ 删除: {dir_path}")
                    removed_count += 1
            except Exception as e:
                print(f"  ✗ 错误删除 {dir_path}: {e}")
    
    print()
    print("📄 清理文件...")
    
    # 删除文件
    for file_pattern in files_to_remove:
        if '*' in file_pattern:
            # 处理通配符
            for root, dirs, files in os.walk('.'):
                # 跳过 git 目录
                if '.git' in dirs:
                    dirs.remove('.git')
                
                import fnmatch
                for file in files:
                    if fnmatch.fnmatch(file, file_pattern):
                        file_path = os.path.join(root, file)
                        try:
                            os.remove(file_path)
                            print(f"  ✓ 删除: {file_path}")
                            removed_count += 1
                        except Exception as e:
                            print(f"  ✗ 错误删除 {file_path}: {e}")
        else:
            if os.path.exists(file_pattern):
                try:
                    os.remove(file_pattern)
                    print(f"  ✓ 删除: {file_pattern}")
                    removed_count += 1
                except Exception as e:
                    print(f"  ✗ 错误删除 {file_pattern}: {e}")
    
    # 创建必要的占位符目录
    print()
    print("📁 创建数据目录占位符...")
    
    placeholder_dirs = [
        'data/plugins',
        'data/config',
        'data/temp',
    ]
    
    for dir_path in placeholder_dirs:
        os.makedirs(dir_path, exist_ok=True)
        # 创建 .gitkeep 文件
        gitkeep = os.path.join(dir_path, '.gitkeep')
        Path(gitkeep).touch()
        print(f"  ✓ 创建: {dir_path}/ (.gitkeep)")
    
    # 验证 .gitignore
    print()
    print("🔍 验证 .gitignore...")
    
    gitignore_content = """# Python related
__pycache__
.mypy_cache
.venv*
.conda/
uv.lock
.coverage

# IDE and editors
.vscode
.idea

# Logs and temporary files
botpy.log
logs/
temp
cookies.json

# Data files
data_v2.db
data_v3.db
data_v4.db
data
configs/session
configs/config.yaml
cmd_config.json
*.db
*.sqlite

# Plugins
addons/plugins
astrbot/builtin_stars/python_interpreter/workplace
tests/astrbot_plugin_openai

# Dashboard
dashboard/node_modules/
dashboard/dist/
.pnpm-store/
package-lock.json
yarn.lock

# Bundled dashboard dist (generated by hatch_build.py during pip wheel build)
astrbot/dashboard/dist/

# Operating System
**/.DS_Store
.DS_Store

# LordSlack specific
.lordslack
lordslack.lock

# Other
chroma
venv/*
pytest.ini
.env
.env.local

# genie_tts data
CharacterModels/
GenieData/
.agent/
.codex/
.opencode/
.kilocode/
.worktrees/

dashboard/bun.lock

# Build and dist
dist/
build/
*.egg-info/
"""
    
    if not os.path.exists('.gitignore'):
        with open('.gitignore', 'w', encoding='utf-8') as f:
            f.write(gitignore_content)
        print("  ✓ 创建新的 .gitignore")
    else:
        print("  ✓ .gitignore 已存在")
    
    # 最终总结
    print()
    print("=" * 60)
    print(f"✅ 清理完成！共处理 {removed_count} 项")
    print("=" * 60)
    print()
    print("后续步骤:")
    print("1. 检查: git status")
    print("2. 提交: git add -A && git commit -m 'chore: prepare for GitHub release'")
    print("3. 推送: git push origin main")
    print()
    print("⚠️  提示:")
    print("- 删除的 data/ 目录已创建占位符，用户首次运行时会自动初始化")
    print("- 确保没有敏感信息被提交到 git 历史记录中")
    print("- 更多详情见: PRE_PUSH_CHECKLIST.md")
    print()

if __name__ == '__main__':
    response = input("确认要清理项目吗？此操作会删除个人数据！(y/N): ")
    if response.lower() == 'y':
        cleanup_for_github()
        print("✨ 项目已清理完毕，可以安全地推送到 GitHub！")
    else:
        print("取消操作。")
