name: '🐛 Report Bug / 报告 Bug'
title: '[Bug]'
description: Submit bug report to help us improve. / 提交报告帮助我们改进。
labels: [ 'bug' ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this issue! Please describe your problem accurately. If possible, please provide a reproducible snippet (this will help resolve the issue more quickly). Please note that issues that are not detailed or have no logs will be closed immediately. Thank you for your understanding. / 感谢您抽出时间报告问题！请准确解释您的问题。如果可能，请提供一个可复现的片段（这有助于更快地解决问题）。请注意，不详细 / 没有日志的 issue 会被直接关闭，谢谢理解。
  - type: textarea
    attributes:
      label: What happened / 发生了什么
      description: Description
      placeholder: >
        Please provide a clear and specific description of what this exception is. Please note that issues that are not detailed or have no logs will be closed immediately. Thank you for your understanding. / 一个清晰且具体的描述这个异常是什么。请注意，不详细 / 没有日志的 issue 会被直接关闭，谢谢理解。
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduce / 如何复现？
      description: >
        The steps to reproduce the issue. / 复现该问题的步骤
      placeholder: >
        Example: 1. Open '...'
    validations:
      required: true

  - type: textarea
    attributes:
      label: 摆烂仙君 version, deployment method (e.g., Windows Docker Desktop deployment), provider used, and messaging platform used. / 摆烂仙君 版本、部署方式（如 Windows Docker Desktop 部署）、使用的提供商、使用的消息平台适配器
      placeholder: >
        Example: 4.5.7 Docker, 3.1.7 Windows Launcher
    validations:
      required: true

  - type: dropdown
    attributes:
      label: OS
      description: |
        On which operating system did you encounter this problem? / 你在哪个操作系统上遇到了这个问题？
      multiple: false
      options:
        - 'Windows'
        - 'macOS'
        - 'Linux'
        - 'Other'
        - 'Not sure'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Logs / 报错日志
      description: >
        Please provide complete Debug-level logs, such as error logs and screenshots. Don't worry if they're long! Please note that issues with insufficient details or no logs will be closed immediately. Thank you for your understanding. / 如报错日志、截图等。请提供完整的 Debug 级别的日志，不要介意它很长！请注意，不详细 / 没有日志的 issue 会被直接关闭，谢谢理解。
      placeholder: >
        Please provide a complete error log or screenshot. / 请提供完整的报错日志或截图。
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR? / 你愿意提交 PR 吗？
      description: >
        This is not required, but we would be happy to provide guidance during the contribution process, especially if you already have a good understanding of how to implement the fix. / 这不是必需的，但我们很乐意在贡献过程中为您提供指导特别是如果你已经很好地理解了如何实现修复。
      options:
        - label: Yes!

  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: >
            I have read and agree to abide by the project's [Code of Conduct](https://docs.github.com/zh/site-policy/github-terms/github-community-code-of-conduct)。
          required: true

  - type: markdown
    attributes:
      value: "Thank you for filling out our form! / 感谢您填写我们的表单！"
